package org.lemandog;

import org.lemandog.Frames.GameMenu;
import org.lemandog.Frames.MenuSettings;
import org.lemandog.enums.miskData;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.image.PixelReader;
import javafx.scene.layout.BorderPane;
import javafx.scene.paint.Color;
import javafx.scene.text.Text;
import javafx.stage.Stage;

import javax.swing.*;
import java.io.*;
import java.util.Objects;

public class Utility {
    static private final Image palette = new Image(Objects.requireNonNull(getImageRes("/utility/pallete1.png")));
    static private final PixelReader inPix = palette.getPixelReader();
    static String documentsPath = new JFileChooser().getFileSystemView().getDefaultDirectory().getPath() + File.separator + "My Games"+ File.separator +"StarFighter";


    public static Color getColorFromPallete(int i) {
        if(i<palette.getWidth()){
            return inPix.getColor(i,0);
        }
        else {return Color.RED;}
    }

    public static void constructInfoFrame() {
        BorderPane layout = new BorderPane();
        Image backg = new Image(Objects.requireNonNull(getImageRes("/menu/info.png")),960,550, false, false);
        ImageView backgV3 = new ImageView(backg);
        backgV3.setOpacity(0.4);

        Text data1 = new Text("You are STARFIGHTER. One of many. \n" +
                "Your planet was invaded by forces of unknown origin \n" +
                "They are more advanced. Their numbers are immeasurable. \n" +
                "Governments of whole EARTH created a training program \n" +
                "for the best of the best. Gladly, you were a great figter pilot, \n" +
                "even before the invasion. So you applied.\n" +
                "Engineers created state of art engines, able for interstellar flight \n" +
                "Your mission is to get to enemy base, making way for bombers\n"
        );
        data1.setFill(Utility.getColorFromPallete(19));
        data1.setFont(GameMenu.font2);
        data1.setStroke(Utility.getColorFromPallete(16));
        Text data2 = new Text("Press S & W or ARROWS for navigation in menus \n" +
                "Press ENTER to select menu \n" +
                "IN GAME: \n" +
                "Press A & D to steer your spaceship \n" +
                "Salvage upgrades from enemies \n" +
                "Press SPACE or ENTER for special firemode \n");
        data2.setFill(Utility.getColorFromPallete(19));
        data2.setFont(GameMenu.font2);
        data2.setStroke(Utility.getColorFromPallete(16));
        Stage info = new Stage();
        info.setResizable(false);
        info.setTitle("CONTROLS and INFO");
        Image icon = new Image(Objects.requireNonNull(getImageRes("/menu/icon.png")));
        info.getIcons().add(icon);

        Scene infoData = new Scene(layout,960,550);
        layout.getChildren().add(backgV3);
        layout.setBottom(data2);
        layout.setTop(data1);
        infoData.setFill(Color.BLACK);
        info.setScene(infoData);
        info.show();
    }
    public static void constructAuthorFrame() {
        BorderPane layout = new BorderPane();
        Image backg = new Image(Objects.requireNonNull(getImageRes("/menu/info.png")),960,550, false, false);
        ImageView backgV3 = new ImageView(backg);
        backgV3.setOpacity(0.4);

        Text data1 = new Text(" This game was made by Lemandog, Aldegida and Groza.\n" +
                "   Latest version available on Lemandog`s github\n" +
                "   This game is distributed on share-free basis, if someone sold \n" +
                "you this game you were lied to.\n" +
                "\n"+
                "   You are free to make any changes, but you cannot \n" +
                "use original code and resources to make non share-free software \n" +
                "   No known interest were broken\n" +
                "\n" +
                "GRAPHICS (3D models and pixelart): Aldegida\n" +
                "CODE, MINOR GRAPHICS AND FONT: Lemandog \n" +
                "TEA AND MORAL SUPPORT: Groza \n"
        );
        data1.setFill(Utility.getColorFromPallete(19));
        data1.setFont(GameMenu.font2);
        data1.setStroke(Utility.getColorFromPallete(16));
        Text data2 = new Text("SOFTWARE USED: \n" +
                "BLENDER v2.91, ASEPRITE v1.2 \n" +
                "MUSIC GENERATED BY TRICK COMPOSER v1.4\n" +
                "CODED IN IntelliJ IDEA Community Edition 2020 with JAVAFX");
        data2.setFill(Utility.getColorFromPallete(19));
        data2.setFont(GameMenu.font2);
        data2.setStroke(Utility.getColorFromPallete(16));
        Stage info = new Stage();
        info.setResizable(false);
        info.setTitle("AUTHORS");
        Image icon = new Image(Objects.requireNonNull(getImageRes("/menu/icon.png")));
        info.getIcons().add(icon);

        Scene infoData = new Scene(layout,960,550);
        layout.getChildren().add(backgV3);
        layout.setBottom(data2);
        layout.setTop(data1);
        infoData.setFill(Color.BLACK);
        info.setScene(infoData);
        info.show();
    }

    public static String getImageRes(String path){
        try{
            return Objects.requireNonNull(Utility.class.getResource(path)).toExternalForm();
        }catch (NullPointerException e){
            Utility.debugOutput("NO SUCH FILE!");
            return null;
        }
    }


    public static int loadLevelLen(int i) {
        return miskData.values()[i].levelLength;
    }
    public static void debugOutput(String text) {
            if(MenuSettings.showDebug){
                System.out.println(text);
            }
    }
}
